// Placeholder: Service worker managed by Workbox generateSW
// This file is kept for reference but the actual SW is generated by vite-plugin-pwa
// All offline sync logic is handled client-side in src/lib/storage.ts
